on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - .github/workflows/**
  #     - "*.sh"

# env:
#   release: ${{ GITHUB_SHA }}

jobs:
  macos:
    runs-on: macos-10.15
    strategy:
      matrix:
        build_type: [Release]
      fail-fast: false
    env:
      platform: macos
      build_type: ${{ matrix.build_type }}
      artifact_name: "libmembraneskia.dylib"
    steps:
      - uses: actions/checkout@v2
      - run: ./csource/check_release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ./csource/download_skia.sh
      - run: ./csource/compile_macosx.sh
      - uses: actions/upload-artifact@v2
        with:
          name: libmembraneskia.dylib
          path: csource/libmembraneskia.dylib
      - run: ./csource/release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    strategy:
      matrix:
        build_type: [Release]
      fail-fast: false
    env:
      platform: linux
      build_type: ${{ matrix.build_type }}
      artifact_name: "libmembraneskia.so"
    steps:
      - uses: actions/checkout@v2
      - run: ./csource/check_release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ./csource/prepare_linux.sh
      - run: ./csource/download_skia.sh
      - run: ./csource/compile_linux.sh
      - uses: actions/upload-artifact@v2
        with:
          name: libmembraneskia.so
          path: csource/libmembraneskia.so
      - run: ./csource/release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
